name: GameManager
version: ${project.version}
main: com.nivyox.gamemanager.GameManagerCore
authors: [Nivyox]
description: Gamemanager project for local Spigot game servers
website: https://nivyox.com
